// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Kernloom Contributors

// Package context defines Kernloom's vendor-neutral context model.
//
// Context answers "what is known about an entity right now?" — it supplies
// facts to Risk Engines and PDPs without itself making policy decisions.
//
// Processing stages:
//
//	Source system → PIP/Read Adapter → VendorAssessment → normalization
//	→ CanonicalContextFact → [Risk Engine | Config PDP | Runtime PDP]
//
// Core invariants:
//   - Vendor assessments are never silently treated as canonical enterprise facts.
//   - Every fact has provenance, observation time and a validity window.
//   - Missing, stale, conflicting and unknown values are explicit states.
//   - Context does not decide policy; it supplies facts to decision components.
//   - Sensitive context is minimised and access-controlled.
package context

import "time"

// FactStatus describes whether a context fact is usable.
type FactStatus string

const (
	// FactStatusKnown: fact is fresh, has sufficient confidence, and is usable.
	FactStatusKnown FactStatus = "known"

	// FactStatusMissing: fact has no value; the PIP did not provide it.
	FactStatusMissing FactStatus = "missing"

	// FactStatusStale: fact exists but has exceeded its maximum age.
	FactStatusStale FactStatus = "stale"

	// FactStatusConflicting: two or more sources provided incompatible values.
	FactStatusConflicting FactStatus = "conflicting"

	// FactStatusUnknown: fact exists but its reliability cannot be determined.
	FactStatusUnknown FactStatus = "unknown"
)

// EntityRef is a canonical reference to an entity in Kernloom's context model.
// It uses stable, vendor-neutral identifiers.
//
// Type examples: "subject", "device", "resource", "session", "workload"
// Ref  examples: "subject:alice@example.com", "device:device-abc", "resource:payroll-api"
type EntityRef struct {
	Type string `yaml:"type" json:"type"`
	Ref  string `yaml:"ref"  json:"ref"`
}

// Causality records whether this fact originated from a Kernloom action,
// preventing feedback loops where Kernloom-generated events escalate risk.
type Causality struct {
	// TraceID links this fact to a distributed trace.
	TraceID string `yaml:"traceId,omitempty" json:"traceId,omitempty"`

	// Origin describes the ultimate source: "external" or "kernloom_action".
	Origin string `yaml:"origin,omitempty" json:"origin,omitempty"`

	// ActionGenerated is true when this fact was produced as a side effect
	// of a Kernloom runtime action (e.g. removing a role attribute).
	// Learning guards and risk engines must exclude action-generated facts.
	ActionGenerated bool `yaml:"actionGenerated,omitempty" json:"actionGenerated,omitempty"`

	// ParentDecisionID links back to the decision that triggered this.
	ParentDecisionID string `yaml:"parentDecisionId,omitempty" json:"parentDecisionId,omitempty"`
}

// Provenance records where a fact came from and how it was produced.
type Provenance struct {
	// SourceAdapter identifies the PIP or read adapter (e.g. "posture-pip", "idp-pip").
	SourceAdapter string `yaml:"sourceAdapter" json:"sourceAdapter"`

	// SourceType describes the collection method: "pip_read", "manual", "derived".
	SourceType string `yaml:"sourceType" json:"sourceType"`

	// PIPInstanceID identifies the specific PIP instance.
	PIPInstanceID string `yaml:"pipInstanceId,omitempty" json:"pipInstanceId,omitempty"`

	// CollectedAt is when the adapter collected the raw value.
	CollectedAt time.Time `yaml:"collectedAt" json:"collectedAt"`

	// MappingVersion is the version of the normalization mapping used.
	// Empty for directly canonical facts.
	MappingVersion string `yaml:"mappingVersion,omitempty" json:"mappingVersion,omitempty"`

	// Causality tracks whether this fact was generated by a Kernloom action.
	Causality Causality `yaml:"causality,omitempty" json:"causality,omitempty"`
}

// DataQuality describes the reliability and freshness of a fact.
type DataQuality struct {
	// Confidence is the reliability score from 0.0 (unreliable) to 1.0 (certain).
	Confidence float64 `yaml:"confidence" json:"confidence"`

	// MaxAge is the maximum acceptable age; facts older than this become stale.
	MaxAge time.Duration `yaml:"maxAge,omitempty" json:"maxAge,omitempty"`
}

// ContextFact is a single canonical, vendor-neutral fact about an entity.
//
// Example:
//
//	Key:       "device.posture.status"
//	Value:     "healthy"
//	EntityRef: {Type: "device", Ref: "device:device-abc"}
//	Status:    FactStatusKnown
type ContextFact struct {
	// Key is the canonical context key from the registry (e.g. "device.posture.status").
	// Must be registered in the ContextKeyRegistry.
	Key string `yaml:"key" json:"key"`

	// Value is the canonical value. Type is defined by the registry key definition.
	Value any `yaml:"value" json:"value"`

	// EntityRef identifies the entity this fact belongs to.
	EntityRef EntityRef `yaml:"entityRef" json:"entityRef"`

	// Provenance records the origin of this fact.
	Provenance Provenance `yaml:"provenance" json:"provenance"`

	// Quality describes the reliability of this fact.
	Quality DataQuality `yaml:"quality" json:"quality"`

	// ObservedAt is when the underlying event or state was observed.
	ObservedAt time.Time `yaml:"observedAt" json:"observedAt"`

	// ValidUntil is when this fact expires. Zero means no expiry.
	ValidUntil time.Time `yaml:"validUntil,omitempty" json:"validUntil,omitempty"`

	// Status describes usability: known, missing, stale, conflicting, unknown.
	Status FactStatus `yaml:"status" json:"status"`
}

// IsUsable returns true when the fact is known and not stale.
func (f *ContextFact) IsUsable() bool {
	if f.Status != FactStatusKnown {
		return false
	}
	if !f.ValidUntil.IsZero() && time.Now().After(f.ValidUntil) {
		return false
	}
	return true
}

// VendorAssessment is a raw vendor-owned interpretation that has NOT yet been
// normalised into a canonical ContextFact.
//
// The key remains vendor-namespaced (e.g. "posture_provider.posture_result").
// It must never be silently treated as a canonical fact.
// A normalization rule must explicitly define the mapping.
//
// Example:
//
//	Vendor:    "posture_provider"
//	Key:       "posture_provider.posture_result" ← vendor-namespaced
//	Value:     "pass"
//	MappedTo:  "device.posture.status"      ← canonical key, after normalization
type VendorAssessment struct {
	// Vendor identifies the source vendor system (e.g. "posture_provider", "edr", "idp").
	Vendor string `yaml:"vendor" json:"vendor"`

	// Key is the vendor-specific, namespaced key. Must start with vendor name.
	// E.g.: "posture_provider.posture_result", "edr.device_risk_level".
	Key string `yaml:"key" json:"key"`

	// Value is the raw vendor value, before normalization.
	Value any `yaml:"value" json:"value"`

	// EntityRef identifies the entity in vendor-specific terms.
	EntityRef EntityRef `yaml:"entityRef" json:"entityRef"`

	// MappedTo is the canonical key this maps to (e.g. "device.posture.status").
	// Empty if no normalization mapping exists.
	MappedTo string `yaml:"mappedTo,omitempty" json:"mappedTo,omitempty"`

	// FidelityNote documents precision loss when the mapping is a semantic downgrade.
	FidelityNote string `yaml:"fidelityNote,omitempty" json:"fidelityNote,omitempty"`

	// Provenance records the origin of this vendor assessment.
	Provenance Provenance `yaml:"provenance" json:"provenance"`

	// ObservedAt is when the vendor system produced this assessment.
	ObservedAt time.Time `yaml:"observedAt" json:"observedAt"`
}

// ContextSnapshot is an immutable, versioned set of context facts for a scope.
// Used for: local simulation, CI validation, reproducible Config PDP decisions,
// audit, replay, and offline KLIQ operation.
//
// Forge may publish signed snapshots embedded in RuntimeBundles.
type ContextSnapshot struct {
	// ID is a unique identifier for this snapshot.
	ID string `yaml:"id" json:"id"`

	// SnapshotAt is when the snapshot was taken.
	SnapshotAt time.Time `yaml:"snapshotAt" json:"snapshotAt"`

	// ValidUntil is when this snapshot expires for simulation/validation purposes.
	ValidUntil time.Time `yaml:"validUntil" json:"validUntil"`

	// ContextRegistryVersion pins the registry version used to validate these facts.
	ContextRegistryVersion string `yaml:"contextRegistryVersion" json:"contextRegistryVersion"`

	// Facts are the canonical context facts at snapshot time.
	Facts []ContextFact `yaml:"facts,omitempty" json:"facts,omitempty"`

	// VendorAssessments are raw vendor assessments included for audit/replay.
	VendorAssessments []VendorAssessment `yaml:"vendorAssessments,omitempty" json:"vendorAssessments,omitempty"`

	// EntityLinks record approved or candidate aliases across PIPs.
	EntityLinks []EntityLink `yaml:"entityLinks,omitempty" json:"entityLinks,omitempty"`

	// PIPHealth records source availability at snapshot time.
	PIPHealth []PIPHealth `yaml:"pipHealth,omitempty" json:"pipHealth,omitempty"`
}

// FactsFor returns all facts in the snapshot that belong to the given entity.
func (s *ContextSnapshot) FactsFor(ref EntityRef) []ContextFact {
	var out []ContextFact
	for _, f := range s.Facts {
		if f.EntityRef.Type == ref.Type && f.EntityRef.Ref == ref.Ref {
			out = append(out, f)
		}
	}
	return out
}

// FactByKey returns the first fact with the given canonical key, or nil.
func (s *ContextSnapshot) FactByKey(key string) *ContextFact {
	for i := range s.Facts {
		if s.Facts[i].Key == key {
			return &s.Facts[i]
		}
	}
	return nil
}

// PIPHealth describes the operational state of a PIP/read adapter.
// A degraded or unavailable PIP affects the usability of facts it supplies.
type PIPHealth struct {
	// SourceAdapter identifies the adapter (e.g. "posture-pip", "idp-pip").
	SourceAdapter string `yaml:"sourceAdapter" json:"sourceAdapter"`

	// Status: "healthy", "degraded", "unavailable".
	Status string `yaml:"status" json:"status"`

	// Healthy is true when Status == "healthy".
	Healthy bool `yaml:"healthy" json:"healthy"`

	// EventLagSeconds is the current ingestion lag for event-based PIPs.
	EventLagSeconds float64 `yaml:"eventLagSeconds,omitempty" json:"eventLagSeconds,omitempty"`

	// LastSeenAt is when the PIP last successfully produced a fact.
	LastSeenAt time.Time `yaml:"lastSeenAt" json:"lastSeenAt"`

	// Details is a human-readable status message.
	Details string `yaml:"details,omitempty" json:"details,omitempty"`
}

// EntityLink connects source-specific identifiers to a canonical entity.
type EntityLink struct {
	Subject      EntityRef   `yaml:"subject" json:"subject"`
	Aliases      []EntityRef `yaml:"aliases,omitempty" json:"aliases,omitempty"`
	Confidence   float64     `yaml:"confidence" json:"confidence"`
	Approved     bool        `yaml:"approved,omitempty" json:"approved,omitempty"`
	Source       string      `yaml:"source,omitempty" json:"source,omitempty"`
	ObservedAt   time.Time   `yaml:"observedAt,omitempty" json:"observedAt,omitempty"`
	EvidenceRefs []string    `yaml:"evidenceRefs,omitempty" json:"evidenceRefs,omitempty"`
}

// RequiredSignal declares a canonical context key that a policy condition needs.
// Used by the compiler and Config PDP to identify missing or unavailable context.
type RequiredSignal struct {
	// PolicyID identifies the policy that requires this signal.
	PolicyID string `yaml:"policyId" json:"policyId"`

	// RequirementID identifies the specific condition within the policy.
	RequirementID string `yaml:"requirementId" json:"requirementId"`

	// ContextKey is the canonical registry key needed (e.g. "device.posture.status").
	ContextKey string `yaml:"contextKey" json:"contextKey"`

	// Providers lists known PIP adapters that can supply this key.
	// Empty means no known provider has been registered.
	Providers []string `yaml:"providers,omitempty" json:"providers,omitempty"`

	// Mandatory: if true, the absence of this signal blocks the policy (fail-closed).
	// If false, missing signal may degrade coverage but not block.
	Mandatory bool `yaml:"mandatory" json:"mandatory"`

	// OnMissing defines runtime PDP behavior when the signal is unavailable.
	// Values: "deny" | "observe_only" | "require_step_up" | "allow_with_audit"
	OnMissing string `yaml:"onMissing" json:"onMissing"`
}
